# Copyright 2024 Thomas M. Parks <tmparks@yahoo.com>

services:
  develop:
    build: .
    volumes:
      - .:/${COMPOSE_PROJECT_NAME} # directory where this file resides
      - ${PWD}:${PWD}              # directory from which docker compose is run
    working_dir: ${PWD}
    user: nobody:cdrom
    devices:
      - /dev/cdrom
